# -*- coding: utf-8 -*-
"""
/***************************************************************************
 a
                                 A QGIS plugin
 v
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-02
        copyright            : (C) 2025 by fdfdfdfdfdfd
        email                : perdas@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'fdfdfdfdfdfd'
__date__ = '2025-10-02'
__copyright__ = '(C) 2025 by fdfdfdfdfdfd'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load a class from file a.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .e import aPlugin
    return aPlugin()
